//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryNewsCount
    {
        public int CategoryId { get; set; }
        public int DirectNewsCount { get; set; }
        public int TotalNewsCount { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
